# coding=utf-8

SOURCE_BUILD = '13187581'

VERBS = frozenset(['action', 'actionIsDisplay', 'appear', 'atlasText', 'blockProperty', 'blurLayer', 'blurMap', 'catch', 'catchProperty', 'changeDispatch', 'child', 'childParentScope', 'class', 'clickSplit', 'clipboard', 'clock', 'collectionDH', 'collectionDesign', 'collectionFields', 'collectionRepeatDH', 'colorTransform', 'concat', 'contains', 'controller', 'countdown', 'dataRefDH', 'directEvent', 'dispatch', 'dispatchDelayReset', 'dragCursor', 'draggable', 'draggableWindow', 'droppable', 'entityDH', 'event', 'eventSequence', 'fade', 'file', 'firstEntityDH', 'generator', 'generatorDH', 'gui', 'handleEventDH', 'imeEnable', 'indexOf', 'inoutAction', 'input', 'instance', 'keyboard', 'lag', 'mc', 'menu', 'pluralText', 'popup', 'popupNoCache', 'primaryEntityDH', 'repeat', 'repeatCache', 'repeatObject', 'request', 'resize', 'restrictFeedback', 'scopeHoldRepeat', 'scopeTrace', 'scrollController', 'scrollControllerCentered', 'serverTime', 'soundOn', 'stageSize', 'style', 'substitute', 'sync', 'timeFormat', 'timeline', 'timestampTween', 'tooltip', 'transition', 'ubFocus', 'vTileHack', 'var', 'visible', 'watch', 'watchDH'])

ELEMENT_TYPES = {
    '': 'block',
    'block': 'block',
    'element': 'element',
    'gblock': 'gblock',
    'native': 'native',
    'text': 'text',
    'ublock': 'ublock',
}
UNKNOWN_TYPE_BECOMES = 'element'

TOP_LEVEL_TAGS = frozenset(['block', 'css'])
BLOCK_CHILD_TAGS = frozenset(['bind', 'block', 'default_text', 'innerBind', 'params', 'style', 'styleClass'])
CHILD_TAG_NEEDS_TYPE = {'default_text': 'text', 'innerBind': 'native'}
NATIVE_SELF = frozenset(['isMask', 'ubFocus', 'visible'])
REQUIRES_BLOCK_HOST = frozenset(['actionIsDisplay', 'atlasText', 'blockProperty', 'class', 'collectionRepeatDH', 'generator', 'generatorDH', 'instance', 'mc', 'repeat', 'repeatCache', 'repeatObject', 'resize', 'scopeHoldRepeat', 'scrollController', 'scrollControllerCentered', 'vTileHack'])
CONSTRUCT = {
    'child': (2, 'child'),
    'childParentScope': (2, 'child'),
    'collectionRepeatDH': (2, 1),
    'generator': (2, 1),
    'generatorDH': (2, 1),
    'instance': (2, 0),
    'menu': (1, 0),
    'popup': (3, 0),
    'popupNoCache': (3, 0),
    'repeat': (2, 1),
    'repeatCache': (7, 1),
    'repeatObject': (2, 1),
    'scopeHoldRepeat': (3, 1),
    'tooltip': (1, 0),
}

TAG_ATTRS = {
    'bind': frozenset(['debug_info', 'name', 'value']),
    'block': frozenset(['className', 'permanent_id', 'type']),
    'css': frozenset(['name']),
    'default_text': frozenset(['value']),
    'innerBind': frozenset(['debug_info', 'elementName', 'name', 'value']),
    'param': frozenset(['name', 'value']),
    'params': frozenset(),
    'style': frozenset(),
    'styleClass': frozenset(['value']),
}

STYLE = {
    'align': ('flags', frozenset(['bottom', 'center', 'justify', 'left', 'middle', 'right', 'top'])),
    'alpha': ('number', ()),
    'background9Slice': ('object', ()),
    'backgroundColor': ('hex', ()),
    'backgroundImage': ('string', ()),
    'backgroundRepeatX': ('boolean', ()),
    'backgroundRepeatY': ('boolean', ()),
    'backgroundSize': ('enum', frozenset(['align', 'autosize', 'contain', 'cover', 'crop', 'empty', 'fill', 'repeat'])),
    'blurFilter': ('filter', ('BlurFilter',)),
    'bottom': ('dimension', ()),
    'colorMatrixFilter': ('filter', ('ColorMatrixFilter',)),
    'dropShadowFilter': ('filter', ('DropShadowFilter',)),
    'flow': ('enum', frozenset(['horizontal', 'htile', 'vertical', 'vtile'])),
    'fontFamily': ('string', ()),
    'fontSize': ('fontSize', ()),
    'generatorOffsetBottom': ('number', ()),
    'generatorOffsetLeft': ('number', ()),
    'generatorOffsetRight': ('number', ()),
    'generatorOffsetTop': ('number', ()),
    'glowFilter': ('filter', ('GlowFilter',)),
    'height': ('dimension', ()),
    'hitTest': ('boolean', ()),
    'itemHeight': ('dimension', ()),
    'itemWidth': ('dimension', ()),
    'itemsBetweenOffset': ('dimension', ()),
    'itemsBottomOffset': ('dimension', ()),
    'itemsLeftOffset': ('dimension', ()),
    'itemsRightOffset': ('dimension', ()),
    'itemsTopOffset': ('dimension', ()),
    'layout': ('string', ()),
    'leading': ('number', ()),
    'left': ('dimension', ()),
    'letterSpacing': ('number', ()),
    'margin': ('rect', ('|',)),
    'marginBottom': ('dimension', ()),
    'marginLeft': ('dimension', ()),
    'marginRight': ('dimension', ()),
    'marginText': ('rect', ('|',)),
    'marginTop': ('dimension', ()),
    'maxHeight': ('number', ()),
    'maxWidth': ('number', ()),
    'mcSizeAbsolute': ('boolean', ()),
    'minHeight': ('number', ()),
    'minWidth': ('number', ()),
    'mouseChildren': ('boolean', ()),
    'mouseEnabled': ('boolean', ()),
    'mouseEnabledWhileScroll': ('boolean', ()),
    'multiline': ('boolean', ()),
    'noTranslate': ('boolean', ()),
    'overflow': ('enum', frozenset(['hidden', 'scroll', 'visible'])),
    'padding': ('rect', ('|',)),
    'paddingBottom': ('dimension', ()),
    'paddingLeft': ('dimension', ()),
    'paddingRight': ('dimension', ()),
    'paddingTop': ('dimension', ()),
    'position': ('enum', frozenset(['absolute', 'relative', 'virtual'])),
    'revertFlow': ('boolean', ()),
    'right': ('dimension', ()),
    'scrollArea': ('string', ()),
    'scrollbar': ('string', ()),
    'scrollbarAlign': ('enum', frozenset(['center', 'justify', 'left', 'right'])),
    'scrollbarController': ('string', ()),
    'scrollbarTrackMode': ('string', ()),
    'selectable': ('boolean', ()),
    'styleSheet': ('string', ()),
    'text': ('string', ()),
    'textAlign': ('enum', frozenset(['center', 'justify', 'left', 'right'])),
    'textColor': ('hex', ()),
    'top': ('dimension', ()),
    'underline': ('boolean', ()),
    'userData': ('object', ()),
    'wheelScrollSpeed': ('dimension', ()),
    'width': ('dimension', ()),
}

TARGETS = {
    'block': {
        'dynamic': False,
        'chain': ('lesta.unbound.layout.UbBlock', 'flash.display.Sprite', 'flash.display.DisplayObjectContainer', 'flash.display.InteractiveObject', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsSettings', 'blendMode', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'currentImagePath', 'doubleClickEnabled', 'dropTarget', 'elementName', 'enabled', 'factory', 'filters', 'focusRect', 'generator', 'graphics', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'layout', 'layoutManager', 'left', 'loaderInfo', 'mask', 'mouseChildren', 'mouseEnabled', 'mouseX', 'mouseY', 'name', 'nativeHeight', 'nativeNativeX', 'nativeNativeY', 'nativeWidth', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'numChildren', 'opaqueBackground', 'parent', 'permanentId', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stage', 'stageRemoveTime', 'style', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'textSnapshot', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsEnabled', 'bindingsSettings', 'blendMode', 'blendShader', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'doubleClickEnabled', 'enabled', 'filters', 'focusRect', 'generator', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'left', 'mask', 'mouseChildren', 'mouseEnabled', 'name', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'opaqueBackground', 'permanentId', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stageRemoveTime', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addChild', 'addChildAt', 'addChildProperly', 'addEventListener', 'addStyleClass', 'addVisibilityListener', 'areInaccessibleObjectsUnderPoint', 'commonStyleDirtyChecks', 'contains', 'dispatchEvent', 'free', 'getBindingsTarget', 'getBounds', 'getChildAt', 'getChildByName', 'getChildIndex', 'getFactory', 'getFiltersTarget', 'getObjectsUnderPoint', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'invalidate', 'invalidateChildren', 'invalidateStageRelativeChildren', 'isDeepDirty', 'local3DToGlobal', 'localToGlobal', 'onAddedToParent', 'playSound', 'propagateParentProps', 'recomputeStyle', 'removeChild', 'removeChildAt', 'removeChildProperly', 'removeEventListener', 'removeStyleClass', 'removeVisibilityListener', 'requestSoftKeyboard', 'scrollTo', 'setBaseStyle', 'setChildIndex', 'setElementName', 'setFactory', 'setFocusBinding', 'setFocused', 'setScroll', 'setUIStatisticsCallback', 'startDrag', 'startTouchDrag', 'stopDrag', 'stopTouchDrag', 'swapChildren', 'swapChildrenAt', 'toString', 'updateLayout', 'willTrigger']),
    },
    'element': {
        'dynamic': False,
        'chain': ('lesta.unbound.layout.UbBlock', 'flash.display.Sprite', 'flash.display.DisplayObjectContainer', 'flash.display.InteractiveObject', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsSettings', 'blendMode', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'currentImagePath', 'doubleClickEnabled', 'dropTarget', 'elementName', 'enabled', 'factory', 'filters', 'focusRect', 'generator', 'graphics', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'layout', 'layoutManager', 'left', 'loaderInfo', 'mask', 'mouseChildren', 'mouseEnabled', 'mouseX', 'mouseY', 'name', 'nativeHeight', 'nativeNativeX', 'nativeNativeY', 'nativeWidth', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'numChildren', 'opaqueBackground', 'parent', 'permanentId', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stage', 'stageRemoveTime', 'style', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'textSnapshot', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsEnabled', 'bindingsSettings', 'blendMode', 'blendShader', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'doubleClickEnabled', 'enabled', 'filters', 'focusRect', 'generator', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'left', 'mask', 'mouseChildren', 'mouseEnabled', 'name', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'opaqueBackground', 'permanentId', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stageRemoveTime', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addChild', 'addChildAt', 'addChildProperly', 'addEventListener', 'addStyleClass', 'addVisibilityListener', 'areInaccessibleObjectsUnderPoint', 'commonStyleDirtyChecks', 'contains', 'dispatchEvent', 'free', 'getBindingsTarget', 'getBounds', 'getChildAt', 'getChildByName', 'getChildIndex', 'getFactory', 'getFiltersTarget', 'getObjectsUnderPoint', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'invalidate', 'invalidateChildren', 'invalidateStageRelativeChildren', 'isDeepDirty', 'local3DToGlobal', 'localToGlobal', 'onAddedToParent', 'playSound', 'propagateParentProps', 'recomputeStyle', 'removeChild', 'removeChildAt', 'removeChildProperly', 'removeEventListener', 'removeStyleClass', 'removeVisibilityListener', 'requestSoftKeyboard', 'scrollTo', 'setBaseStyle', 'setChildIndex', 'setElementName', 'setFactory', 'setFocusBinding', 'setFocused', 'setScroll', 'setUIStatisticsCallback', 'startDrag', 'startTouchDrag', 'stopDrag', 'stopTouchDrag', 'swapChildren', 'swapChildrenAt', 'toString', 'updateLayout', 'willTrigger']),
    },
    'gblock': {
        'dynamic': False,
        'chain': ('lesta.unbound.layout.GamefaceElementBlock', 'lesta.unbound.layout.UbBlock', 'flash.display.Sprite', 'flash.display.DisplayObjectContainer', 'flash.display.InteractiveObject', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsSettings', 'blendMode', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'currentImagePath', 'doubleClickEnabled', 'dropTarget', 'elementName', 'enabled', 'factory', 'filters', 'focusRect', 'generator', 'graphics', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'layout', 'layoutManager', 'left', 'loaderInfo', 'mask', 'mouseChildren', 'mouseEnabled', 'mouseX', 'mouseY', 'name', 'nativeHeight', 'nativeNativeX', 'nativeNativeY', 'nativeWidth', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'numChildren', 'opaqueBackground', 'parent', 'permanentId', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stage', 'stageRemoveTime', 'style', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'textSnapshot', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsEnabled', 'bindingsSettings', 'blendMode', 'blendShader', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'doubleClickEnabled', 'enabled', 'filters', 'focusRect', 'gamefaceName', 'gamefacePath', 'gamefaceViewId', 'generator', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'left', 'mask', 'mouseChildren', 'mouseEnabled', 'name', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'opaqueBackground', 'permanentId', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stageRemoveTime', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addChild', 'addChildAt', 'addChildProperly', 'addEventListener', 'addStyleClass', 'addVisibilityListener', 'areInaccessibleObjectsUnderPoint', 'commonStyleDirtyChecks', 'contains', 'dispatchEvent', 'free', 'getBindingsTarget', 'getBounds', 'getChildAt', 'getChildByName', 'getChildIndex', 'getFactory', 'getFiltersTarget', 'getObjectsUnderPoint', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'invalidate', 'invalidateChildren', 'invalidateStageRelativeChildren', 'isDeepDirty', 'local3DToGlobal', 'localToGlobal', 'onAddedToParent', 'playSound', 'propagateParentProps', 'recomputeStyle', 'removeChild', 'removeChildAt', 'removeChildProperly', 'removeEventListener', 'removeStyleClass', 'removeVisibilityListener', 'requestSoftKeyboard', 'scrollTo', 'setBaseStyle', 'setChildIndex', 'setElementName', 'setFactory', 'setFocusBinding', 'setFocused', 'setScroll', 'setUIStatisticsCallback', 'startDrag', 'startTouchDrag', 'stopDrag', 'stopTouchDrag', 'swapChildren', 'swapChildrenAt', 'toString', 'updateLayout', 'willTrigger']),
    },
    'native': {
        'dynamic': False,
        'chain': ('lesta.unbound.layout.UbNativeBlock', 'lesta.unbound.layout.UbBlock', 'flash.display.Sprite', 'flash.display.DisplayObjectContainer', 'flash.display.InteractiveObject', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsSettings', 'blendMode', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'currentImagePath', 'doubleClickEnabled', 'dropTarget', 'elementName', 'enabled', 'factory', 'filters', 'focusRect', 'generator', 'graphics', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'isMask', 'layout', 'layoutManager', 'left', 'loaderInfo', 'mask', 'mouseChildren', 'mouseEnabled', 'mouseX', 'mouseY', 'name', 'nativeChild', 'nativeHeight', 'nativeNativeX', 'nativeNativeY', 'nativeWidth', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'numChildren', 'opaqueBackground', 'parent', 'permanentId', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stage', 'stageRemoveTime', 'style', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'textSnapshot', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsEnabled', 'bindingsSettings', 'blendMode', 'blendShader', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'doubleClickEnabled', 'enabled', 'filters', 'focusRect', 'generator', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'isMask', 'left', 'mask', 'mouseChildren', 'mouseEnabled', 'name', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'opaqueBackground', 'permanentId', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stageRemoveTime', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addChild', 'addChildAt', 'addChildProperly', 'addEventListener', 'addStyleClass', 'addVisibilityListener', 'areInaccessibleObjectsUnderPoint', 'commonStyleDirtyChecks', 'contains', 'dispatchEvent', 'free', 'getBindingsTarget', 'getBounds', 'getChildAt', 'getChildByName', 'getChildIndex', 'getFactory', 'getFiltersTarget', 'getObjectsUnderPoint', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'invalidate', 'invalidateChildren', 'invalidateStageRelativeChildren', 'isDeepDirty', 'local3DToGlobal', 'localToGlobal', 'onAddedToParent', 'playSound', 'propagateParentProps', 'recomputeStyle', 'removeChild', 'removeChildAt', 'removeChildProperly', 'removeEventListener', 'removeStyleClass', 'removeVisibilityListener', 'requestSoftKeyboard', 'scrollTo', 'setBaseStyle', 'setChildIndex', 'setElementName', 'setFactory', 'setFocusBinding', 'setFocused', 'setNativeChild', 'setScroll', 'setUIStatisticsCallback', 'startDrag', 'startTouchDrag', 'stopDrag', 'stopTouchDrag', 'swapChildren', 'swapChildrenAt', 'toString', 'updateLayout', 'willTrigger']),
    },
    'root': {
        'dynamic': False,
        'chain': ('lesta.unbound.layout.UbRootBlock', 'lesta.unbound.layout.UbBlock', 'flash.display.Sprite', 'flash.display.DisplayObjectContainer', 'flash.display.InteractiveObject', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsSettings', 'blendMode', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'currentImagePath', 'doubleClickEnabled', 'dropTarget', 'elementName', 'enabled', 'factory', 'filters', 'focusRect', 'generator', 'graphics', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'layout', 'layoutManager', 'left', 'loaderInfo', 'mask', 'mouseChildren', 'mouseEnabled', 'mouseX', 'mouseY', 'name', 'nativeHeight', 'nativeNativeX', 'nativeNativeY', 'nativeWidth', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'numChildren', 'opaqueBackground', 'parent', 'permanentId', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stage', 'stageRemoveTime', 'style', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'textSnapshot', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsEnabled', 'bindingsSettings', 'blendMode', 'blendShader', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'doubleClickEnabled', 'enabled', 'filters', 'focusRect', 'generator', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'left', 'mask', 'mouseChildren', 'mouseEnabled', 'name', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'opaqueBackground', 'permanentId', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stageRemoveTime', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addChild', 'addChildAt', 'addChildProperly', 'addEventListener', 'addStyleClass', 'addVisibilityListener', 'areInaccessibleObjectsUnderPoint', 'commonStyleDirtyChecks', 'contains', 'dispatchEvent', 'free', 'getBindingsTarget', 'getBounds', 'getChildAt', 'getChildByName', 'getChildIndex', 'getFactory', 'getFiltersTarget', 'getObjectsUnderPoint', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'invalidate', 'invalidateChildren', 'invalidateStageRelativeChildren', 'isDeepDirty', 'local3DToGlobal', 'localToGlobal', 'onAddedToParent', 'playSound', 'propagateParentProps', 'recomputeStyle', 'removeChild', 'removeChildAt', 'removeChildProperly', 'removeEventListener', 'removeStyleClass', 'removeVisibilityListener', 'requestSoftKeyboard', 'scrollTo', 'setBaseStyle', 'setChildIndex', 'setElementName', 'setFactory', 'setFocusBinding', 'setFocused', 'setScroll', 'setUIStatisticsCallback', 'startDrag', 'startTouchDrag', 'stopDrag', 'stopTouchDrag', 'swapChildren', 'swapChildrenAt', 'toString', 'updateLayout', 'willTrigger']),
    },
    'text': {
        'dynamic': False,
        'chain': ('lesta.unbound.layout.UbTextBlock', 'lesta.unbound.layout.UbBlock', 'flash.display.Sprite', 'flash.display.DisplayObjectContainer', 'flash.display.InteractiveObject', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsSettings', 'blendMode', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'currentImagePath', 'doubleClickEnabled', 'dropTarget', 'elementName', 'enabled', 'factory', 'filters', 'focusRect', 'generator', 'graphics', 'height', 'hitArea', 'id', 'intValue', 'invalidateChildrenTime', 'layout', 'layoutManager', 'left', 'loaderInfo', 'mask', 'mouseChildren', 'mouseEnabled', 'mouseX', 'mouseY', 'name', 'nativeHeight', 'nativeNativeX', 'nativeNativeY', 'nativeWidth', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'numChildren', 'opaqueBackground', 'parent', 'permanentId', 'pureText', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stage', 'stageRemoveTime', 'style', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'text', 'textField', 'textFormat', 'textSnapshot', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsEnabled', 'bindingsSettings', 'blendMode', 'blendShader', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'doubleClickEnabled', 'enabled', 'filters', 'focusRect', 'generator', 'height', 'hitArea', 'id', 'intValue', 'invalidateChildrenTime', 'left', 'mask', 'mouseChildren', 'mouseEnabled', 'name', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'opaqueBackground', 'permanentId', 'pureText', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stageRemoveTime', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'text', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addChild', 'addChildAt', 'addChildProperly', 'addEventListener', 'addStyleClass', 'addVisibilityListener', 'areInaccessibleObjectsUnderPoint', 'commonStyleDirtyChecks', 'contains', 'dispatchEvent', 'free', 'getBindingsTarget', 'getBounds', 'getChildAt', 'getChildByName', 'getChildIndex', 'getFactory', 'getFiltersTarget', 'getObjectsUnderPoint', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'invalidate', 'invalidateChildren', 'invalidateStageRelativeChildren', 'invalidateText', 'isDeepDirty', 'local3DToGlobal', 'localToGlobal', 'onAddedToParent', 'playSound', 'propagateParentProps', 'recomputeStyle', 'removeChild', 'removeChildAt', 'removeChildProperly', 'removeEventListener', 'removeStyleClass', 'removeVisibilityListener', 'requestSoftKeyboard', 'scrollTo', 'setBaseStyle', 'setChildIndex', 'setElementName', 'setFactory', 'setFocusBinding', 'setFocused', 'setOnTextChangedUIStatisticsCallback', 'setScroll', 'setUIStatisticsCallback', 'startDrag', 'startTouchDrag', 'stopDrag', 'stopTouchDrag', 'swapChildren', 'swapChildrenAt', 'toString', 'updateLayout', 'willTrigger']),
    },
    'ublock': {
        'dynamic': False,
        'chain': ('lesta.unbound.layout.UbElementBlock', 'lesta.unbound.layout.UbBlock', 'flash.display.Sprite', 'flash.display.DisplayObjectContainer', 'flash.display.InteractiveObject', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsSettings', 'blendMode', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'currentImagePath', 'doubleClickEnabled', 'dropTarget', 'element', 'elementHeight', 'elementName', 'elementWidth', 'enabled', 'factory', 'filters', 'focusRect', 'generator', 'graphics', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'layout', 'layoutManager', 'left', 'loaderInfo', 'mask', 'mouseChildren', 'mouseEnabled', 'mouseX', 'mouseY', 'name', 'nativeHeight', 'nativeNativeX', 'nativeNativeY', 'nativeWidth', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'numChildren', 'opaqueBackground', 'parent', 'permanentId', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stage', 'stageRemoveTime', 'style', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'textSnapshot', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'bindings', 'bindingsEnabled', 'bindingsSettings', 'blendMode', 'blendShader', 'buttonMode', 'cacheAsBitmap', 'childCreationQueue', 'computedStyle', 'contextMenu', 'doubleClickEnabled', 'enabled', 'externalArgs', 'filters', 'focusRect', 'generator', 'height', 'hitArea', 'id', 'invalidateChildrenTime', 'left', 'mask', 'mouseChildren', 'mouseEnabled', 'name', 'nativeX', 'nativeY', 'needsSoftKeyboard', 'opaqueBackground', 'permanentId', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'softKeyboardInputAreaOfInterest', 'soundSet', 'soundTransform', 'stackVisibility', 'stageRemoveTime', 'styleFragments', 'tabChildren', 'tabEnabled', 'tabIndex', 'top', 'transform', 'ubScaleX', 'ubScaleY', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addChild', 'addChildAt', 'addChildProperly', 'addEventListener', 'addStyleClass', 'addVisibilityListener', 'areInaccessibleObjectsUnderPoint', 'build', 'commonStyleDirtyChecks', 'contains', 'dispatchEvent', 'free', 'getBindingsTarget', 'getBounds', 'getChildAt', 'getChildByName', 'getChildIndex', 'getFactory', 'getFiltersTarget', 'getObjectsUnderPoint', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'invalidate', 'invalidateChildren', 'invalidateStageRelativeChildren', 'isDeepDirty', 'local3DToGlobal', 'localToGlobal', 'onAddedToParent', 'playSound', 'propagateParentProps', 'recomputeStyle', 'removeChild', 'removeChildAt', 'removeChildProperly', 'removeEventListener', 'removeStyleClass', 'removeVisibilityListener', 'requestSoftKeyboard', 'scrollTo', 'setBaseStyle', 'setChildIndex', 'setElementName', 'setFactory', 'setFocusBinding', 'setFocused', 'setScroll', 'setUIStatisticsCallback', 'setUb1ParentSize', 'startDrag', 'startTouchDrag', 'stopDrag', 'stopTouchDrag', 'swapChildren', 'swapChildrenAt', 'toString', 'updateLayout', 'willTrigger']),
    },
}

NATIVE_CLASSES = {
    'lesta.display.Circle': {
        'dynamic': False,
        'chain': ('lesta.display.Circle', 'lesta.display.Primitive', 'flash.display.Shape', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityProperties', 'alpha', 'alphas', 'bitmap', 'bitmapFillMatrix', 'blendMode', 'cacheAsBitmap', 'color', 'colors', 'filters', 'graphics', 'height', 'interpolationMethod', 'lineAlpha', 'lineColor', 'lineThickness', 'loaderInfo', 'mask', 'mouseX', 'mouseY', 'name', 'opaqueBackground', 'parent', 'radius', 'ratios', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'spreadMethod', 'stage', 'transform', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityProperties', 'alpha', 'alphas', 'bitmap', 'bitmapFillMatrix', 'blendMode', 'blendShader', 'cacheAsBitmap', 'color', 'colors', 'filters', 'height', 'interpolationMethod', 'lineAlpha', 'lineColor', 'lineThickness', 'mask', 'name', 'opaqueBackground', 'radius', 'ratios', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'spreadMethod', 'transform', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addEventListener', 'dispatchEvent', 'getBounds', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'local3DToGlobal', 'localToGlobal', 'removeEventListener', 'toString', 'willTrigger']),
    },
    'lesta.display.MapPath': {
        'dynamic': False,
        'chain': ('lesta.display.MapPath', 'flash.display.Sprite', 'flash.display.DisplayObjectContainer', 'flash.display.InteractiveObject', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'approximation', 'blendMode', 'buttonMode', 'cacheAsBitmap', 'canvasH', 'canvasW', 'contextMenu', 'dashSize', 'doubleClickEnabled', 'dropTarget', 'filters', 'focusRect', 'graphics', 'height', 'hitArea', 'loaderInfo', 'mask', 'mouseChildren', 'mouseEnabled', 'mouseX', 'mouseY', 'name', 'needsSoftKeyboard', 'numChildren', 'opaqueBackground', 'parent', 'pathNodes', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'shadowAlpha', 'shadowAngle', 'shadowBlurX', 'shadowBlurY', 'shadowColor', 'shadowDistance', 'shadowHideObject', 'shadowInner', 'shadowKnockout', 'shadowQuality', 'shadowStrength', 'softKeyboardInputAreaOfInterest', 'soundTransform', 'spaceSize', 'stage', 'tabChildren', 'tabEnabled', 'tabIndex', 'tension', 'textSnapshot', 'transform', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityImplementation', 'accessibilityProperties', 'alpha', 'approximation', 'blendMode', 'blendShader', 'buttonMode', 'cacheAsBitmap', 'contextMenu', 'dashSize', 'doubleClickEnabled', 'filters', 'focusRect', 'height', 'hitArea', 'linestyles', 'mask', 'mouseChildren', 'mouseEnabled', 'name', 'needsSoftKeyboard', 'opaqueBackground', 'pathNodes', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'shadowAlpha', 'shadowAngle', 'shadowBlurX', 'shadowBlurY', 'shadowColor', 'shadowDistance', 'shadowHideObject', 'shadowInner', 'shadowKnockout', 'shadowQuality', 'shadowStrength', 'softKeyboardInputAreaOfInterest', 'soundTransform', 'spaceSize', 'states', 'tabChildren', 'tabEnabled', 'tabIndex', 'tension', 'transform', 'useHandCursor', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addChild', 'addChildAt', 'addEventListener', 'areInaccessibleObjectsUnderPoint', 'contains', 'dispatchEvent', 'getBounds', 'getChildAt', 'getChildByName', 'getChildIndex', 'getObjectsUnderPoint', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'local3DToGlobal', 'localToGlobal', 'removeChild', 'removeChildAt', 'removeEventListener', 'requestSoftKeyboard', 'setChildIndex', 'startDrag', 'startTouchDrag', 'stopDrag', 'stopTouchDrag', 'swapChildren', 'swapChildrenAt', 'toString', 'willTrigger']),
    },
    'lesta.display.Sector': {
        'dynamic': False,
        'chain': ('lesta.display.Sector', 'lesta.display.Circle', 'lesta.display.Primitive', 'flash.display.Shape', 'flash.display.DisplayObject', 'flash.events.EventDispatcher'),
        'read': frozenset(['accessibilityProperties', 'alpha', 'alphas', 'arc', 'bitmap', 'bitmapFillMatrix', 'blendMode', 'cacheAsBitmap', 'color', 'colors', 'filters', 'graphics', 'height', 'innerRadius', 'interpolationMethod', 'lineAlpha', 'lineColor', 'lineThickness', 'loaderInfo', 'mask', 'mouseX', 'mouseY', 'name', 'offset', 'opaqueBackground', 'parent', 'radius', 'ratios', 'root', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'spreadMethod', 'stage', 'transform', 'visible', 'width', 'x', 'y', 'z']),
        'write': frozenset(['accessibilityProperties', 'alpha', 'alphas', 'arc', 'bitmap', 'bitmapFillMatrix', 'blendMode', 'blendShader', 'cacheAsBitmap', 'color', 'colors', 'filters', 'height', 'innerRadius', 'interpolationMethod', 'lineAlpha', 'lineColor', 'lineThickness', 'mask', 'name', 'offset', 'opaqueBackground', 'radius', 'ratios', 'rotation', 'rotationX', 'rotationY', 'rotationZ', 'scale9Grid', 'scaleX', 'scaleY', 'scaleZ', 'scrollRect', 'spreadMethod', 'transform', 'visible', 'width', 'x', 'y', 'z']),
        'methods': frozenset(['addEventListener', 'dispatchEvent', 'getBounds', 'getRect', 'globalToLocal', 'globalToLocal3D', 'hasEventListener', 'hitTestObject', 'hitTestPoint', 'local3DToGlobal', 'localToGlobal', 'removeEventListener', 'toString', 'willTrigger']),
    },
}

STYLE_OBJECT_WRITE = frozenset(['adaptations', 'align', 'alpha', 'background9Slice', 'backgroundColor', 'backgroundImage', 'backgroundImageData', 'backgroundRepeatX', 'backgroundRepeatY', 'backgroundSize', 'blurFilter', 'bottom', 'bottomMode', 'colorMatrixFilter', 'dirty', 'dropShadowFilter', 'flow', 'fontFamily', 'fontSize', 'fontSizeMode', 'generatorOffsetBottom', 'generatorOffsetLeft', 'generatorOffsetRight', 'generatorOffsetTop', 'glowFilter', 'height', 'heightMode', 'hitTest', 'itemHeight', 'itemHeightMode', 'itemWidth', 'itemWidthMode', 'itemsBetweenOffset', 'itemsBetweenOffsetMode', 'itemsBottomOffset', 'itemsBottomOffsetMode', 'itemsLeftOffset', 'itemsLeftOffsetMode', 'itemsRightOffset', 'itemsRightOffsetMode', 'itemsTopOffset', 'itemsTopOffsetMode', 'layout', 'leading', 'left', 'leftMode', 'letterSpacing', 'margin', 'marginBottom', 'marginBottomMode', 'marginLeft', 'marginLeftMode', 'marginRight', 'marginRightMode', 'marginText', 'marginTop', 'marginTopMode', 'maskExtender', 'maxHeight', 'maxWidth', 'mcSizeAbsolute', 'minHeight', 'minWidth', 'mouseChildren', 'mouseEnabled', 'mouseEnabledWhileScroll', 'multiline', 'noTranslate', 'overflow', 'padding', 'paddingBottom', 'paddingBottomMode', 'paddingLeft', 'paddingLeftMode', 'paddingRight', 'paddingRightMode', 'paddingTop', 'paddingTopMode', 'position', 'revertFlow', 'right', 'rightMode', 'scaleX', 'scaleY', 'scrollArea', 'scrollLeft', 'scrollPosition', 'scrollTop', 'scrollbar', 'scrollbarAlign', 'scrollbarController', 'scrollbarTrackMode', 'selectable', 'styleSheet', 'textAlign', 'textColor', 'top', 'topMode', 'underline', 'userData', 'wheelScrollSpeed', 'wheelScrollSpeedMode', 'width', 'widthMode'])

SOURCE_FINGERPRINTS = {
    'lesta.dialogs.ScaleformMovie': '8266308f2e13b7ed',
    'lesta.libs.unbound.ActionIsDisplayBinding': '87fdde35856cd714',
    'lesta.libs.unbound.ColorTransformBinding': '8b5b8414468f94de',
    'lesta.libs.unbound.ConcatBinding': '5676bf3724177168',
    'lesta.libs.unbound.DHCollectionBinding': '992fffb3084aa1a2',
    'lesta.libs.unbound.DHCollectionGeneratorBinding': '36ec477e314dc90a',
    'lesta.libs.unbound.DHCollectionRepeatBinding': '237982b47faffe55',
    'lesta.libs.unbound.DHDataRefBinding': '8a29013f9fdc5c83',
    'lesta.libs.unbound.DHEntityBinding': 'e9e51e89eda5aa29',
    'lesta.libs.unbound.DHFirstEntityBinding': '996c501d18a209b9',
    'lesta.libs.unbound.DHHandleEventBinding': 'b627057104086dcb',
    'lesta.libs.unbound.DHPrimaryEntityBinding': 'd608595b02b8d98b',
    'lesta.libs.unbound.DHWatchBinding': '66c130d898d9b5cf',
    'lesta.libs.unbound.DesignerCollectionBinding': 'c804c16b2c213af1',
    'lesta.libs.unbound.GSTimelineBinding': '96b47fa0647dbdd8',
    'lesta.libs.unbound.InputMappingBinding': '3d78c685127e2398',
    'lesta.libs.unbound.SFMActionBinding': 'f7584e9034afa1ff',
    'lesta.libs.unbound.SFMEventBinding': '04b69cf39ea70a05',
    'lesta.libs.unbound.SFMGuiBinding': 'd347cd6538c45c37',
    'lesta.libs.unbound.SFMRequestBinding': '81359510c6974959',
    'lesta.libs.unbound.UBCollectionFieldsBinding': '512aef417c11cccc',
    'lesta.libs.unbound.UBScrollBinding': '0bbabdd4caa0b7cd',
    'lesta.libs.unbound.UBScrollBindingCentered': '94da91342d8ca0ca',
    'lesta.libs.unbound.UbDirectEventBinding': '8061e0621a2899be',
    'lesta.libs.unbound.UbDraggableBinding': '10847b5444bc74fb',
    'lesta.libs.unbound.UbDroppableBinding': '6c32656f3bcc67c1',
    'lesta.libs.unbound.UbEventPlaySoundBinding': '21a133b32cea0419',
    'lesta.libs.unbound.UbFocusBinding': '03b723c84fc697f2',
    'lesta.libs.unbound.UbInOutActionBinding': 'f2a7cd1e697f2d4c',
    'lesta.libs.unbound.UbLagBinding': '6072f4de0e7dff17',
    'lesta.libs.unbound.WowsResizeBinding': 'f145dc8297d60147',
    'lesta.unbound.bindings.DHBinding': '53215888e3c6cad5',
    'lesta.unbound.bindings.MovieClipBinding': '5e0ebc1c82f7ea2a',
    'lesta.unbound.bindings.UBClickSplitBinding': '8670ad00231ea523',
    'lesta.unbound.bindings.UBRepeatObjectBinding': '958bfa0a8d065261',
    'lesta.unbound.bindings.UBServerTimeBinding': '072e62b8f32bc229',
    'lesta.unbound.bindings.UBVariablesBinding': 'ea06e1cbc238582e',
    'lesta.unbound.bindings.UbAppearBinding': 'b7c67dde4c05d0d7',
    'lesta.unbound.bindings.UbBinding': '4ee7c939b4b3fb02',
    'lesta.unbound.bindings.UbBlockBinding': 'ffa77ed61a00e895',
    'lesta.unbound.bindings.UbBlurLayerBinding': 'd14c091087991edb',
    'lesta.unbound.bindings.UbBlurMapBinding': '936b943bfd563a18',
    'lesta.unbound.bindings.UbCatchEventBinding': 'a8b3deb25e8c92e9',
    'lesta.unbound.bindings.UbCatchPropertyBinding': '02c0e6da9851e65a',
    'lesta.unbound.bindings.UbChangeDispatchBinding': '6de454ba583ef3c7',
    'lesta.unbound.bindings.UbChildBinding': '2b04a2b4f4f96ad6',
    'lesta.unbound.bindings.UbChildParentScopeBinding': '2ae744a0397e5894',
    'lesta.unbound.bindings.UbClipboardEventBinding': 'ef0946a096cf66b2',
    'lesta.unbound.bindings.UbClockBinding': '7e9ee243dfff8474',
    'lesta.unbound.bindings.UbContainsBinding': 'bdb08ab7a712e714',
    'lesta.unbound.bindings.UbContextMenuBinding': 'c9030ce93d8bb205',
    'lesta.unbound.bindings.UbControllerBinding': '9f2515df908f5ce0',
    'lesta.unbound.bindings.UbCountdownBinding': '7e76c8e0fb501e80',
    'lesta.unbound.bindings.UbDispatchBinding': '350354e6ea3746a2',
    'lesta.unbound.bindings.UbDispatchDelayResetBinding': '8c501d80fb9ebe01',
    'lesta.unbound.bindings.UbDispatchMultiDelayBinding': 'bfcda809c65b230d',
    'lesta.unbound.bindings.UbDragCursorBinding': '6da57a4d8af0345e',
    'lesta.unbound.bindings.UbDraggableBindingWindow': '8e84dff13d442479',
    'lesta.unbound.bindings.UbEventBinding': '17262d79e6f7a3c6',
    'lesta.unbound.bindings.UbEventSequenceBinding': '52ba7081de98c16f',
    'lesta.unbound.bindings.UbFadeBinding': '222cebb909038e83',
    'lesta.unbound.bindings.UbFileBinding': '5243cd21a97f37c9',
    'lesta.unbound.bindings.UbGeneratorBinding': 'b1c34054275a2e5f',
    'lesta.unbound.bindings.UbIMEEnableBinding': 'edc7ebcb9c36f427',
    'lesta.unbound.bindings.UbIndexOfBinding': '0c3784c5d53997bf',
    'lesta.unbound.bindings.UbInstanceBinding': '8709f8d54515dea6',
    'lesta.unbound.bindings.UbKeyboardBinding': 'bac5d4768e267b15',
    'lesta.unbound.bindings.UbPluralTextBinding': '53b32bec85f615ee',
    'lesta.unbound.bindings.UbPopupBinding': 'bd450493e44381be',
    'lesta.unbound.bindings.UbPropertyBinding': '48769a388d6e2c46',
    'lesta.unbound.bindings.UbRepeatBinding': '61b83927454a4946',
    'lesta.unbound.bindings.UbRepeatBindingBase': 'cfd91150975e4840',
    'lesta.unbound.bindings.UbRepeatBindingCache': '9d7e748ec266e375',
    'lesta.unbound.bindings.UbRepeatWithScopeHoldBinding': '511af9c5b3349548',
    'lesta.unbound.bindings.UbResizeBinding': '514135168ccbf504',
    'lesta.unbound.bindings.UbRestrictFeedbackBinding': '237ae4247aa6d094',
    'lesta.unbound.bindings.UbScopeTraceBinding': '2e0f391859bd7405',
    'lesta.unbound.bindings.UbStageSizeBinding': '1fc18329772cafba',
    'lesta.unbound.bindings.UbStyleBinding': 'ed6c526875a2a3bc',
    'lesta.unbound.bindings.UbStyleClassBinding': 'bbe5182143b8b2d7',
    'lesta.unbound.bindings.UbSubstituteBinding': '65cb0d7ada3f9916',
    'lesta.unbound.bindings.UbSyncBinding': '64e6ebcce6d33559',
    'lesta.unbound.bindings.UbTextTextureBinding': '71989e3ca80522de',
    'lesta.unbound.bindings.UbTimeFormatBinding': '970c62f9915217ad',
    'lesta.unbound.bindings.UbTimestampTweenBinding': '9289b9d263a86cbc',
    'lesta.unbound.bindings.UbTooltipBinding': 'd7c12d71fc67e800',
    'lesta.unbound.bindings.UbTransitionBinding': '8a99bb153c787531',
    'lesta.unbound.bindings.UbVTileHackBinding': '419b86bafb11fc31',
    'lesta.unbound.bindings.UbVisibleBinding': '602ff0088a683839',
    'lesta.unbound.bindings.UbWatchBinding': '0b4b9026b75b2137',
    'lesta.unbound.bindings.popup.UbPopupNoCacheBinding': '3e0577c7e26e77ac',
    'lesta.unbound.core.UbCentral': 'a383a854e8645c51',
    'lesta.unbound.core.UbCollectionGenerator': '81d61ef1e03b7f40',
    'lesta.unbound.core.UbItemGenerator': '8b3db69b2fe90802',
    'lesta.unbound.expression.UbNativeExpression': '99005cb955d59f33',
    'lesta.unbound.expression.UnboundLoader': '634d24f67380f1fd',
    'lesta.unbound.layout.UbBlockConstructionPlan': 'cd3f985cf0d3722b',
    'lesta.unbound.layout.UbBlockFactory': '4dc3b42d5e1a7a92',
    'lesta.unbound.layout.build.ElementType': 'e76a541a569df82d',
    'lesta.unbound.style.UbStyleParser': '2db10cbbae40ed60',
}
